"""_setStartValueHMI.py
Write StartValue and Comment from an HMI Variables Excel file back into TIA Portal
DB/IDB exports. Reads the Excel file generated by _extractHMI.py and updates the
corresponding XML (.xml) and text (.db) source files.

Dependencies:
    pip install pyyaml openpyxl

If you get:
    ModuleNotFoundError: No module named 'yaml'
install the missing package with:
    pip install pyyaml

Usage:
    python Tools\\_setStartValueHMI.py                             # auto-detect
    python Tools\\_setStartValueHMI.py <xlsx_file>                  # explicit Excel
    python Tools\\_setStartValueHMI.py <xlsx_file> <plc_base_dir>   # explicit both
    python Tools\\_setStartValueHMI.py --help
"""

import argparse
import os
import re
import sys
import xml.etree.ElementTree as ET
from openpyxl import load_workbook

# === Configuration ===

NS = "http://www.siemens.com/automation/Openness/SW/Interface/v5"

BLOCK_TYPES_XML = ("SW.Blocks.GlobalDB", "SW.Blocks.InstanceDB")


# ═══════════════════════════════════════════════════════════════════════════════
#  Utility
# ═══════════════════════════════════════════════════════════════════════════════

def _local_tag(elem):
    """Get local tag name without namespace."""
    tag = elem.tag
    return tag.split("}")[-1] if "}" in tag else tag


def _elem_ns(elem):
    """Get the namespace prefix string from an element's tag (e.g. '{ns}')."""
    if "}" in elem.tag:
        return elem.tag.split("}")[0] + "}"
    return ""


# ═══════════════════════════════════════════════════════════════════════════════
#  Read Excel
# ═══════════════════════════════════════════════════════════════════════════════

def _cell_to_str(val):
    """Convert openpyxl cell value to TIA-compatible start-value string."""
    if val is None:
        return ""
    if isinstance(val, bool):
        return "TRUE" if val else "FALSE"
    if isinstance(val, float):
        if val == int(val) and abs(val) < 1e15:
            return str(int(val))
        return str(val)
    return str(val).strip()


def read_excel_values(xlsx_path):
    """Read Excel → {block_name: {full_path: (start_value, comment)}}.
    Only rows with non-empty start_value or comment are included.
    Array-indexed paths (virtual expansions) are skipped."""
    wb = load_workbook(xlsx_path, read_only=True, data_only=True)
    ws = wb.active

    blocks = {}
    for row in ws.iter_rows(min_row=2, values_only=True):
        if not row or len(row) < 3 or not row[0]:
            continue
        name = str(row[0]).strip()
        start_value = _cell_to_str(row[2])
        comment = str(row[8]).strip() if len(row) > 8 and row[8] is not None else ""
        if not start_value and not comment:
            continue
        # Skip virtual array-element expansions (e.g. Block.Arr[0].Field)
        if re.search(r'\[\d+\]', name):
            continue
        block_name = name.split(".")[0]
        blocks.setdefault(block_name, {})[name] = (start_value, comment)

    wb.close()
    return blocks


# ═══════════════════════════════════════════════════════════════════════════════
#  Build block → file map
# ═══════════════════════════════════════════════════════════════════════════════

_RE_DB_HEADER = re.compile(r'\s*DATA_BLOCK\s+"([^"]+)"')


def build_block_file_map(prog_dir):
    """Map block_name → (filepath, 'xml'|'db') for GlobalDB / InstanceDB files."""
    block_map = {}

    for dirpath, _, files in os.walk(prog_dir):
        for f in files:
            filepath = os.path.join(dirpath, f)

            if f.lower().endswith(".xml"):
                try:
                    tree = ET.parse(filepath)
                except ET.ParseError:
                    continue
                xml_root = tree.getroot()
                for tag in BLOCK_TYPES_XML:
                    block = xml_root.find(f".//{tag}")
                    if block is not None:
                        attr = block.find("AttributeList")
                        if attr is not None:
                            name_elem = attr.find("Name")
                            if name_elem is not None and name_elem.text:
                                block_map[name_elem.text.strip()] = (filepath, "xml")
                        break

            elif f.lower().endswith(".db"):
                try:
                    with open(filepath, "r", encoding="utf-8-sig") as fh:
                        first_line = fh.readline()
                except Exception:
                    continue
                m = _RE_DB_HEADER.match(first_line)
                if m:
                    block_map[m.group(1)] = (filepath, "db")

    return block_map


# ═══════════════════════════════════════════════════════════════════════════════
#  XML Update
# ═══════════════════════════════════════════════════════════════════════════════

def _set_start_value_xml(member, value):
    """Set or update <StartValue> text on a Member element."""
    for child in member:
        if _local_tag(child) == "StartValue":
            child.text = value
            return

    # Create new StartValue element, matching parent namespace
    ns = _elem_ns(member)
    sv = ET.Element(f"{ns}StartValue")
    sv.text = value

    # Insert after AttributeList / Comment, before child Members / Sections
    insert_idx = 0
    for i, child in enumerate(member):
        lt = _local_tag(child)
        if lt in ("AttributeList", "Comment"):
            insert_idx = i + 1
        elif lt in ("Member", "Sections"):
            break
    member.insert(insert_idx, sv)


def _set_comment_xml(member, comment_text):
    """Set or update <Comment><MultiLanguageText Lang='en-US'> on a Member."""
    ns = _elem_ns(member)

    for child in member:
        if _local_tag(child) == "Comment":
            # Update existing en-US text or add it
            for mlt in child:
                if _local_tag(mlt) == "MultiLanguageText" and mlt.get("Lang") == "en-US":
                    mlt.text = comment_text
                    return
            # No en-US entry yet — create one
            mlt = ET.SubElement(child, f"{ns}MultiLanguageText")
            mlt.set("Lang", "en-US")
            mlt.text = comment_text
            return

    # No <Comment> element — create it after <AttributeList>
    comment_elem = ET.Element(f"{ns}Comment")
    mlt = ET.SubElement(comment_elem, f"{ns}MultiLanguageText")
    mlt.set("Lang", "en-US")
    mlt.text = comment_text

    insert_idx = 0
    for i, child in enumerate(member):
        if _local_tag(child) == "AttributeList":
            insert_idx = i + 1
            break
    member.insert(insert_idx, comment_elem)


def _walk_and_update_xml(member, path_parts, path_value_map, updated):
    """Recursively walk Member elements and update StartValue/Comment."""
    name = member.get("Name", "")
    current_path = path_parts + [name]
    full_path = ".".join(current_path)

    if full_path in path_value_map:
        new_sv, new_comment = path_value_map[full_path]
        changed = False

        # --- StartValue ---
        if new_sv:
            old_sv = ""
            for child in member:
                if _local_tag(child) == "StartValue":
                    old_sv = (child.text or "").strip()
                    break
            if old_sv != new_sv:
                _set_start_value_xml(member, new_sv)
                changed = True

        # --- Comment ---
        if new_comment:
            old_comment = ""
            for child in member:
                if _local_tag(child) == "Comment":
                    for mlt in child:
                        if _local_tag(mlt) == "MultiLanguageText" and mlt.get("Lang") == "en-US":
                            old_comment = (mlt.text or "").strip()
                            break
                    break
            if old_comment != new_comment:
                _set_comment_xml(member, new_comment)
                changed = True

        if changed:
            updated.append(full_path)

    # Recurse into child members (direct or via Sections/Section)
    for child in list(member):
        lt = _local_tag(child)
        if lt == "Member":
            _walk_and_update_xml(child, current_path, path_value_map, updated)
        elif lt == "Sections":
            for sec in child:
                if _local_tag(sec) == "Section":
                    for m in sec:
                        if _local_tag(m) == "Member":
                            _walk_and_update_xml(m, current_path, path_value_map,
                                                 updated)


def update_xml_file(filepath, block_name, path_value_map):
    """Update StartValues in an XML DB/IDB file. Returns list of updated paths."""
    ET.register_namespace('', NS)

    try:
        tree = ET.parse(filepath)
    except ET.ParseError:
        return []

    root = tree.getroot()
    updated = []

    for tag in BLOCK_TYPES_XML:
        block = root.find(f".//{tag}")
        if block is None:
            continue

        attr = block.find("AttributeList")
        if attr is None:
            return []

        iface = attr.find("Interface")
        if iface is None:
            return []

        sections = None
        for child in iface:
            if _local_tag(child) == "Sections":
                sections = child
                break
        if sections is None:
            return []

        for section in sections:
            if _local_tag(section) != "Section":
                continue
            for member in section:
                if _local_tag(member) == "Member":
                    _walk_and_update_xml(member, [block_name], path_value_map,
                                         updated)
        break

    if updated:
        tree.write(filepath, encoding="utf-8", xml_declaration=True)
        # Fix single-quoted declaration to double-quoted (TIA Portal compatibility)
        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read()
        content = content.replace(
            "<?xml version='1.0' encoding='utf-8'?>",
            '<?xml version="1.0" encoding="utf-8"?>',
        )
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)

    return updated


# ═══════════════════════════════════════════════════════════════════════════════
#  .db Text File Update
# ═══════════════════════════════════════════════════════════════════════════════

_RE_MEMBER_LINE = re.compile(
    r'^(\s+)'                       # group 1: leading whitespace
    r'(\w+)'                        # group 2: member name
    r'(\s*\{[^}]*\})?\s*'          # group 3: optional {attrs}
    r':\s*'                         # colon separator
    r'(.+)$'                        # group 4: rest (type, :=, ;, // comment)
)


def _rebuild_db_line(indent, name, attrs_str, type_str, new_value, comment):
    """Rebuild a .db member line with a new start value."""
    attrs_part = f" {attrs_str}" if attrs_str else ""
    val_part = f" := {new_value}" if new_value else ""
    comment_part = f"   // {comment}" if comment else ""
    return f"{indent}{name}{attrs_part} : {type_str}{val_part};{comment_part}\n"


def update_db_file(filepath, block_name, path_value_map):
    """Update StartValues and Comments in a .db text file. Returns list of updated paths."""
    try:
        with open(filepath, "rb") as f:
            raw_head = f.read(3)
        has_bom = raw_head == b'\xef\xbb\xbf'
    except Exception:
        has_bom = False

    try:
        with open(filepath, "r", encoding="utf-8-sig") as f:
            lines = f.readlines()
    except Exception:
        return []

    updated = []
    path_stack = []     # struct nesting member names
    in_var = False
    in_begin = False
    new_lines = []

    for line in lines:
        stripped = line.strip()

        if in_begin:
            new_lines.append(line)
            continue

        if stripped.startswith("BEGIN"):
            in_begin = True
            new_lines.append(line)
            continue

        if stripped in ("VAR", "STRUCT") and not in_var:
            in_var = True
            new_lines.append(line)
            continue

        if stripped.startswith("END_VAR") or stripped == "END_STRUCT;":
            if path_stack:
                path_stack.pop()
            else:
                in_var = False
            new_lines.append(line)
            continue

        if not in_var:
            new_lines.append(line)
            continue

        mm = _RE_MEMBER_LINE.match(line)
        if not mm:
            new_lines.append(line)
            continue

        indent = mm.group(1)
        member_name = mm.group(2)
        attrs_str = (mm.group(3) or "").strip()
        rest = mm.group(4)

        # Split comment
        comment = ""
        if "//" in rest:
            rest_main, comment = rest.split("//", 1)
            comment = comment.strip()
            rest_main = rest_main.rstrip()
        else:
            rest_main = rest.rstrip()

        # Split type and old start value
        rest_clean = rest_main.rstrip(";").strip()
        if ":=" in rest_clean:
            type_str, old_val = rest_clean.split(":=", 1)
            type_str = type_str.strip()
            old_val = old_val.strip()
        else:
            type_str = rest_clean.strip()
            old_val = ""

        is_struct = type_str.lower() == "struct"
        full_path = ".".join([block_name] + path_stack + [member_name])

        if full_path in path_value_map:
            new_sv, new_comment = path_value_map[full_path]
            effective_sv = new_sv if new_sv else old_val
            effective_comment = new_comment if new_comment else comment
            if effective_sv != old_val or effective_comment != comment:
                new_line = _rebuild_db_line(indent, member_name, attrs_str,
                                            type_str, effective_sv,
                                            effective_comment)
                updated.append(full_path)
                new_lines.append(new_line)
            else:
                new_lines.append(line)
        else:
            new_lines.append(line)

        if is_struct:
            path_stack.append(member_name)

    if updated:
        enc = "utf-8-sig" if has_bom else "utf-8"
        with open(filepath, "w", encoding=enc) as f:
            f.writelines(new_lines)

    return updated


# ═══════════════════════════════════════════════════════════════════════════════
#  Auto-detection
# ═══════════════════════════════════════════════════════════════════════════════

def find_plc_base(start_dir):
    """Search for a PLC folder containing 'PLC data types' and 'Program blocks'."""
    tia_export = os.path.join(start_dir, "TiaExport")
    search_roots = [tia_export, start_dir] if os.path.isdir(tia_export) else [start_dir]

    for search_root in search_roots:
        for root, dirs, _ in os.walk(search_root):
            if "PLC data types" in dirs and "Program blocks" in dirs:
                return root
            depth = root[len(search_root):].count(os.sep)
            if depth > 7:
                dirs.clear()
    return None


def find_xlsx(start_dir, plc_name):
    """Find the default HMI Variables Excel file in UserFiles/."""
    primary = os.path.join(start_dir, "UserFiles", f"HMI_Variables_{plc_name}.xlsx")
    if os.path.isfile(primary):
        return primary
    # Fallback: any HMI_Variables*.xlsx in UserFiles/
    uf_dir = os.path.join(start_dir, "UserFiles")
    if os.path.isdir(uf_dir):
        for f in sorted(os.listdir(uf_dir)):
            if f.startswith("HMI_Variables") and f.lower().endswith(".xlsx"):
                return os.path.join(uf_dir, f)
    return None


# ═══════════════════════════════════════════════════════════════════════════════
#  Main
# ═══════════════════════════════════════════════════════════════════════════════

def parse_args():
    parser = argparse.ArgumentParser(
        description="Write StartValue and Comment from HMI Variables Excel "
                    "back into TIA Portal DB/IDB exports.",
    )
    parser.add_argument(
        "xlsx", nargs="?", default=None,
        help="Path to the HMI Variables Excel file. "
             "Auto-detects from UserFiles/ if omitted.",
    )
    parser.add_argument(
        "plc_base", nargs="?", default=None,
        help="Path to PLC folder containing 'PLC data types' and "
             "'Program blocks'. Auto-detects if omitted.",
    )
    return parser.parse_args()


def main():
    args = parse_args()

    # --- Resolve PLC base ---
    if args.plc_base:
        plc_base = os.path.abspath(args.plc_base)
    else:
        print("Auto-detecting PLC folder ...")
        plc_base = find_plc_base(os.getcwd())
        if plc_base is None:
            sys.exit(
                "ERROR: Could not find PLC folder.\n"
                "Run from the project root or pass paths as arguments:\n"
                "  python _setStartValueHMI.py <xlsx> <plc_folder>"
            )
        print(f"  Found: {plc_base}")

    plc_name = os.path.basename(plc_base)
    prog_dir = os.path.join(plc_base, "Program blocks")
    if not os.path.isdir(prog_dir):
        sys.exit(f"ERROR: Program blocks directory not found: {prog_dir}")

    # --- Resolve Excel file ---
    if args.xlsx:
        xlsx_path = os.path.abspath(args.xlsx)
    else:
        print("Auto-detecting Excel file ...")
        xlsx_path = find_xlsx(os.getcwd(), plc_name)
        if xlsx_path is None:
            sys.exit(
                "ERROR: Could not find HMI Variables Excel file in UserFiles/.\n"
                "Run _extractHMI.py first, or pass the Excel path as argument."
            )
        print(f"  Found: {xlsx_path}")

    if not os.path.isfile(xlsx_path):
        sys.exit(f"ERROR: Excel file not found: {xlsx_path}")

    # --- Read values from Excel ---
    print("Reading values from Excel ...")
    block_values = read_excel_values(xlsx_path)
    total_values = sum(len(v) for v in block_values.values())
    print(f"  {total_values} entries from {len(block_values)} blocks")

    if not block_values:
        print("  Nothing to update.")
        return

    # --- Build file map ---
    print("Scanning Program blocks ...")
    block_map = build_block_file_map(prog_dir)
    print(f"  {len(block_map)} DB/IDB files found")

    # --- Update files ---
    total_updated = 0
    blocks_updated = 0
    blocks_skipped = []

    for block_name, path_values in sorted(block_values.items()):
        if block_name not in block_map:
            blocks_skipped.append(block_name)
            continue

        filepath, file_type = block_map[block_name]

        if file_type == "xml":
            changes = update_xml_file(filepath, block_name, path_values)
        else:
            changes = update_db_file(filepath, block_name, path_values)

        if changes:
            blocks_updated += 1
            total_updated += len(changes)
            for path in changes:
                print(f"  Updated: {path}")

    if blocks_skipped:
        print(f"\n  WARNING: {len(blocks_skipped)} blocks not found in Program blocks:")
        for bn in blocks_skipped:
            print(f"    - {bn}")

    print(f"\nDone: {total_updated} variables updated in {blocks_updated} blocks")


if __name__ == "__main__":
    main()
